else if (commandName === 'clock-out') {
            if (userClockIn[user.id]) {
                const currentTime = moment().tz('America/Chicago').valueOf();
                const elapsedMilliseconds = currentTime - userClockIn[user.id];
                const elapsedMinutes = Math.floor(elapsedMilliseconds / (1000 * 60));
                const elapsedHours = Math.floor(elapsedMinutes / 60);
                const remainingMinutes = elapsedMinutes % 60;
        
                if (!userStats[user.id]) {
                    userStats[user.id] = {};
                }
                userStats[user.id].hoursAsPD = elapsedHours;
                userStats[user.id].minutesAsPD = remainingMinutes;
                delete userClockIn[user.id];
        
                return interaction.reply({
                    content: `<@${user.id}> has clocked out as PD. Total time as PD: ${elapsedHours} hours and ${remainingMinutes} minutes`,
                });
            } else {
                return interaction.reply({
                    content: `<@${user.id}> is not currently clocked in as PD.`,
                });
            }
        } else if (commandName === 'stats') {
            const userStat = userStats[user.id] || {
                arrests: 0,
                robberies: 0,
                raids: 0,
                hoursAsPD: 0,
                minutesAsPD: 0,
                tickets: 0,
            };
        
            // Replace 'API_ENDPOINT' with the actual API endpoint you are using
            const API_ENDPOINT = 'https://api.svrecco.com:3000/api/PD';
        
            // Assuming user.id is the Discord ID of the currently logged-in user
            const discordid = user.id;
        
            // Make an API request to fetch the user's data
            axios
                .get(API_ENDPOINT)
                .then(async (response) => {
                    const userData = response.data;
        
                    // Check if the user with the specified Discord ID exists in the API response
                    if (userData[discordid]) {
                        const userStatAPI = userData[discordid];
        
                        // Extract the timeAsPD value
                        const timeAsPD =
                            userStatAPI.timeAsPD || '0 hours and 0 minutes';
        
                        // Create formatted statistics
                        const formattedStats = `‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ${
                            userRank[user.id] || 'Use /setrank'
                        }\n`;
                        const formattedStats2 = `‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ <@${user.id}>\n`;
                        const formattedStats3 = `‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ${
                            userStatAPI.robberies || 0
                        }\n`;
                        const formattedStats4 = `‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ${
                            userStatAPI.arrests || 0
                        }\n`;
                        const formattedStats5 = `‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ${
                            userStatAPI.raids || 0
                        }\n`;
                        const formattedStats6 = `${timeAsPD}`;
                        const formattedStats7 = `${
                            userStats[user.id]?.tickets || 0
                        }\n`;
                        const currentDate = new Date().toLocaleString('en-US', {
                            timeZone: 'America/Chicago',
                        });
                        const nickname =
                            interaction.guild.members.cache.get(user.id)?.displayName ||
                            'N/A';
        
                        // Create an example embed
                        const exampleEmbed = new EmbedBuilder()
                            .setColor(0xec0c0d)
                            .setAuthor({
                                name: 'MGRP PD',
                                iconURL:
                                    'https://techstarwebsolutions.com/Icons/LSPD.png',
                                url: 'https://discord.js.org',
                            })
                            .setTitle(`__Statistics Report For ${nickname}__`)
                            .setDescription('*Auto-generated by LSPD BOT version 1.0*')
                            .addFields(
                                {
                                    name:
                                        '───────────────────────────────────',
                                    value: '\u200B',
                                    inline: false,
                                },
                                {
                                    name: '👮 ** Discord Name ** 👮 ',
                                    value: formattedStats2,
                                    inline: true,
                                },
                                {
                                    name: '🛡️ ** Police Rank ** 🛡️ ',
                                    value: formattedStats,
                                    inline: true,
                                },
                                {
                                    name: '\u200B',
                                    value: '\u200B',
                                    inline: false,
                                },
                                {
                                    name: '🏦 ** Robberies ** ‎ ',
                                    value: formattedStats3,
                                    inline: true,
                                },
                                {
                                    name: ':police_car: ** Arrests ** ‎ ',
                                    value: formattedStats4,
                                    inline: true,
                                },
                                {
                                    name: ':crossed_swords: ** Raids ** ‎ ',
                                    value: formattedStats5,
                                    inline: true,
                                },
                                {
                                    name:
                                        '───────────────────────────────────',
                                    value: '\u200B',
                                    inline: false,
                                },
                                {
                                    name: '⏰ ** Time as PD ** ⏰ ',
                                    value: formattedStats6,
                                    inline: true,
                                },
                                {
                                    name: ':ticket: ** Tickets ** :ticket: ',
                                    value: formattedStats7,
                                    inline: false,
                                }
                            )
                            .setFooter({
                                text: `Time Stamp: ${currentDate}`,
                                iconURL:
                                    'https://techstarwebsolutions.com/Icons/CK.png',
                            })
                            .setThumbnail(
                                `https://techstarwebsolutions.com/PD/${user.id}.png`
                            );
        
                        // Send the embed as a reply
                        await interaction.reply({ embeds: [exampleEmbed], ephemeral: true });
                    }
                })
                .catch((error) => {
                    console.error(`Error fetching user data: ${error.message}`);
                });
        }
    }
});